version: '3.3'
services:

    # MONGO DB
    prod_mongo_service:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: the_username
            MONGO_INITDB_ROOT_PASSWORD: the_password
            MONGO_INITDB_DATABASE: the_database
        volumes: 
            - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    
    # REDIS API
    prod_redis_service:
        image: redis:latest
        restart: always
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - ./todo-backend/redis_data:/data

    # EXPRESS API
    prod_backend:
        image: node:16
        restart: always
        depends_on:
            - prod_mongo_service
            - prod_redis_service
        environment:
            MONGO_URL: mongodb://the_username:the_password@prod_mongo_service:27017/the_database
            REDIS_URL: redis://prod_redis_service:6379
            PORT: 3000
        volumes:
            - ./todo-backend/:/backend_files
        working_dir: /backend_files
        command: bash -c "npm install -y && npm start"

    # FRONTEND SERVICE
    prod_frontend:
        image: node:16
        restart: always
        depends_on:
            - prod_backend
        environment:
            REACT_APP_BACKEND_URL: http://localhost:8080/api
        volumes:
            - ./todo-frontend/:/frontend_files
        working_dir: /frontend_files
        command: bash -c
            "
                npm install -y &&
                CI=true npm test &&
                npm run build &&
                npm install -g -y serve &&
                serve build
            "
  
    # REVERSE PROXY FOR FRONTEND & BACKEND
    nginx:
        image: nginx:1.20.1
        depends_on:
            - prod_frontend
            - prod_backend
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:80

# clear && docker-compose -f docker-production.yml down && docker-compose -f docker-production.yml up --remove-orphans --no-recreate