version: '3.3'
services:

    # MONGO DB
    dev_mongo_service:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: the_username
            MONGO_INITDB_ROOT_PASSWORD: the_password
            MONGO_INITDB_DATABASE: the_database
        volumes: 
            - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    
    # REDIS API
    dev_redis_service:
        image: redis:latest
        restart: always
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - ./todo-backend/redis_data:/data

    # EXPRESS API
    dev_backend:
        image: node:16
        restart: always
        depends_on:
            - dev_mongo_service
            - dev_redis_service
        environment:
            MONGO_URL: mongodb://the_username:the_password@dev_mongo_service:27017/the_database
            REDIS_URL: redis://dev_redis_service:6379
            PORT: 3000
        ports:
            - 3001:3000
        volumes:
            - ./todo-backend/:/backend_files
        working_dir: /backend_files
        command: bash -c "npm install -y && npm run dev"

    # FRONTEND SERVICE
    dev_frontend:
        image: node:16
        restart: always
        depends_on:
            - dev_backend
        environment:
            REACT_APP_BACKEND_URL: http://localhost:3001/api/
        ports:
            - 3000:3000
        volumes:
            - ./todo-frontend/:/frontend_files
        working_dir: /frontend_files
        command: bash -c "npm install -y && npm start"

# clear && docker-compose -f docker-development.yml down && docker-compose -f docker-development.yml up --remove-orphans --no-recreate