version: '3.3'
services:

  # MONGO DB
  mongo_service:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  # REDIS API
  redis_service:
    image: redis:latest
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data

  # EXPRESS API
  backend_development:
    image: node:16
    depends_on:
      - mongo_service
      - redis_service
    restart: always
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo_service:27017/the_database
      REDIS_URL: redis://redis_service:6379
      PORT: 3000
    ports:
      - 3011:3000
    volumes:
      - ./:/service_files
    working_dir: /service_files
    command: bash -c "npm install -y && npm run dev"

# clear && docker-compose -f backend-development.yml down && docker-compose -f backend-development.yml up --remove-orphans --no-recreate