version: '3.3'          
services:

  frontend_development:
    image: node:16
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3011
    ports:
      - 3010:3000
    volumes:
      - ./:/service_files
    working_dir: /service_files
    command: bash -c
        "
            npm install -y &&
            npm start
        "

# clear && docker-compose -f frontend-development.yml down && docker-compose -f frontend-development.yml up --remove-orphans --no-recreate